# UR5 Pick and Place Task Configuration

# Environment Configuration
environment:
  # Task settings
  task:
    robot:
      name: "ur5"
    cubes:
      names: ["red_cube", "green_cube", "blue_cube"]
    table:
      name: "table"
    camera:
      name: "Right_Camera"
    ros:
      use_ros: true
      joint_states_topic: "/isaac_joint_states"
      joint_commands_topic: "/isaac_joint_commands"
  
  # Observation settings
  observations:
    device: "cuda:0"
    camera:
      use_camera: true
      use_tiled_cameras: true
      width: 256
      height: 144
      name: "Right_Camera"
  
  # Reward settings
  reward:
    reward_scale: 1.0
    distance_reward_scale: 1.0
    distance_reward_min: -5.0
    approach_reward: 1.0
    grasp_reward: 2.0
    placement_reward: 5.0
    success_reward: 10.0
    movement_penalty_scale: 0.01
  
  # Action settings
  action:
    use_joint_control: true
    num_joints: 7  # 6 arm joints + 1 gripper joint

# PPO Agent Configuration
ppo:
  learning_rate: 3.0e-4
  batch_size: 512
  discount_factor: 0.99
  lambda: 0.95
  clip_range: 0.2
  entropy_coefficient: 0.01
  value_coefficient: 0.5
  learning_epochs: 10
  max_grad_norm: 0.5
  normalize_advantages: true
  update_repeat: 3

# Memory Configuration
memory_size: 24000

# Trainer Configuration
trainer:
  timesteps: 24000
  evaluation_timesteps: 0
  checkpoints: 100000
  checkpoint_path: null
  verbosity: 1