params:
  seed: 42
  env:
    clip_observations: 100.0
    clip_actions: 5.0  
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    inputs:
      # Define which observation name corresponds to which processing type
      rgb_camera: 
        shape: [128, 128, 3]
        embedding_size: 512
        type: conv2d
        conv_activation: elu
        normalize: true
        convs:
          - filters: 32
            kernel_size: 8
            strides: 4
            padding: 0
          - filters: 64
            kernel_size: 4
            strides: 2
            padding: 0
          - filters: 64
            kernel_size: 4
            strides: 1
            padding: 0
          - filters: 128
            kernel_size: 3
            strides: 1
            padding: 0
      policy:
        shape: [31]
        embedding_size: 128
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None
  load_checkpoint: False
  load_path: ''
  config:
    name: pre_grasping_ur5
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 0.0005
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.01
    score_to_win: 10000
    max_epochs: 2500
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 0.01
    entropy_coef: 0.001
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 8192
    mini_epochs: 8
    critic_coef: 2
    clip_value: True
    clip_actions: False
    bounds_loss_coef: 0.0001
    use_diagnostics: True