params:
  seed: 42
  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 5.0
    # can make custom wrapper?
    clip_actions: 5.0
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  # camera-based network configuration
  network:
    name: actor_critic
    separate: True  # Keep separate networks for camera-based training
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    cnn:
      type: conv2d
      activation: elu  # Changed to elu to match your original config
      initializer:
          name: default
      regularizer:
        name: None
      convs:
        - filters: 32
          kernel_size: 8
          strides: 4
          padding: 0
        - filters: 64
          kernel_size: 4
          strides: 2
          padding: 0
        - filters: 64
          kernel_size: 3
          strides: 1
          padding: 0
    mlp:
      units: [256, 128, 64]  # Your original MLP architecture
      activation: elu
      initializer:
          name: default
      regularizer:
        name: None
  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load
  config:
    name: camera_pose_tracking_ur5
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: True  # Keep mixed precision for better performance
    normalize_input: True  # Keep normalization for camera inputs
    normalize_value: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-4  # Using scientific notation format
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.01
    score_to_win: 10000
    max_epochs: 2000  # Your specified training length
    save_best_after: 50
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0005  # Small entropy for exploration
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 24  # Your specified horizon
    minibatch_size: 48 # Your calculated batch size (num envs × 24 horizon)
    mini_epochs: 8
    critic_coef: 2
    clip_value: True
    clip_actions: False
    seq_length: 4  # Added sequence length for potential RNN support
    bounds_loss_coef: 0.0001
    use_diagnostics: False




    