
params:
  seed: 42
  # environment wrapper clipping
  env:
    clip_observations: 100.0
    clip_actions: 5.0  
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 256, 128, 64]  # Network architecture matching our SAC config
      activation: elu    # Using ELU activation like in our SAC config
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None
  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load
  config:
    name: pose_tracking_ur5
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1  # Match our environment's num_envs
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 0.0153  # Standard learning rate for PPO
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.01
    score_to_win: 10000
    max_epochs: 2000  # Set for approximately 45000 steps total
    save_best_after: 200
    save_frequency: 100
    print_stats: True
    grad_norm: 9.2
    entropy_coef: 0.001  # Slightly lower to focus more on exploitation
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 36
    minibatch_size: 73728  # Adjusted based on our environment's size (num envs × 24 horizon)
    mini_epochs: 10
    critic_coef: 2
    clip_value: True
    clip_actions: False  # Already handled by environment
    bounds_loss_coef: 0.0001
    use_diagnostics: True
